export let keys = {
    'Backquote': {
      class: 'button-small',
      inner: true,
      ru: ['ё', 'Ё'],
      en: ['~', '`'],
    },
    'Digit1': {
      class: 'button-small',
      inner: true,
      ru: ['1', '!'],
      en: ['1', '!'],
    },
    'Digit2': {
      class: 'button-small',
      inner: true,
      ru: ['2', '"'],
      en: ['2', '@'],
    },
    'Digit3': {
      class: 'button-small',
      inner: true,
      ru: ['3', '№'],
      en: ['3', '#'],
    },
    'Digit4': {
      class: 'button-small',
      inner: true,
      ru: ['4', ';'],
      en: ['4', '$'],
    },
    'Digit5': {
      class: 'button-small',
      inner: true,
      ru: ['5', '%'],
      en: ['5', '%'],
    },
    'Digit6': {
      class: 'button-small',
      inner: true,
      ru: ['6', ':'],
      en: ['6', '^'],
    },
    'Digit7': {
      class: 'button-small',
      inner: true,
      ru: ['7', '?'],
      en: ['7', '&'],
    },
    'Digit8': {
      class: 'button-small',
      inner: true,
      ru: ['8', '*'],
      en: ['8', '*'],
    },
    'Digit9': {
      class: 'button-small',
      inner: true,
      ru: ['9', '('],
      en: ['9', '('],
    },
    'Digit0': {
      class: 'button-small',
      inner: true,
      ru: ['0', ')'],
      en: ['0', ')'],
    },
    'Minus': {
      class: 'button-small',
      inner: true,
      ru: ['-', '_'],
      en: ['-', '_'],
    },
    'Equal': {
      class: 'button-small',
      inner: true,
      ru: ['=', '+'],
      en: ['=', '+'],
    },
    'Backspace': {
      class: 'button-small backspace',
      inner: false,
      ru: ['Backspace', 'Backspace'],
      en: ['Backspace', 'Backspace'],
    },
    'Tab': {
      class: 'button-small tab',
      inner: false,
      ru: ['Tab', 'Tab'],
      en: ['Tab', 'Tab'],
    },
    'KeyQ': {
      class: 'button-small',
      inner: true,
      ru: ['й', 'Й'],
      en: ['q', 'Q'],
    },
    'KeyW': {
      class: 'button-small',
      inner: true,
      ru: ['ц', 'Ц'],
      en: ['w', 'W'],
    },
    'KeyE': {
      class: 'button-small',
      inner: true,
      ru: ['у', 'У'],
      en: ['e', 'E'],
    },
    'KeyR': {
      class: 'button-small',
      inner: true,
      ru: ['к', 'К'],
      en: ['r', 'R'],
    },
    'KeyT': {
      class: 'button-small',
      inner: true,
      ru: ['е', 'Е'],
      en: ['t', 'T'],
    },
    'KeyY': {
      class: 'button-small',
      inner: true,
      ru: ['н', 'Н'],
      en: ['y', 'Y'],
    },
    'KeyU': {
      class: 'button-small',
      inner: true,
      ru: ['г', 'Г'],
      en: ['u', 'U'],
    },
    'KeyI': {
      class: 'button-small',
      inner: true,
      ru: ['ш', 'Ш'],
      en: ['i', 'I'],
    },
    'KeyO': {
      class: 'button-small',
      inner: true,
      ru: ['щ', 'Щ'],
      en: ['o', 'O'],
    },
    'KeyP': {
      class: 'button-small',
      inner: true,
      ru: ['з', 'З'],
      en: ['p', 'P'],
    },
    'BracketLeft': {
      class: 'button-small',
      inner: true,
      ru: ['х', 'Х'],
      en: ['[', '{'],
    },
    'BracketRight': {
      class: 'button-small',
      inner: true,
      ru: ['ъ', 'Ъ'],
      en: [']', '}'],
    },
    'Backslash': {
      class: 'button-small',
      inner: true,
      ru: ['\\', '/'],
      en: ['\\', '|'],
    },
    'Delete': {
      class: 'button-small del',
      inner: false,
      ru: ['Del', 'Del'],
      en: ['Del', 'Del'],
    },
    'CapsLock': {
      class: 'button-small capslock',
      inner: false,
      ru: ['CapsLk', 'CapsLk'],
      en: ['CapsLk', 'CapsLk'],
    },
    'KeyA': {
      class: 'button-small',
      inner: true,
      ru: ['ф', 'Ф'],
      en: ['a', 'A'],
    },
    'KeyS': {
      class: 'button-small',
      inner: true,
      ru: ['ы', 'Ы'],
      en: ['s', 'S'],
    },
    'KeyD': {
      class: 'button-small',
      inner: true,
      ru: ['в', 'В'],
      en: ['d', 'D'],
    },
    'KeyF': {
      class: 'button-small',
      inner: true,
      ru: ['а', 'А'],
      en: ['f', 'F'],
    },
    'KeyG': {
      class: 'button-small',
      inner: true,
      ru: ['п', 'П'],
      en: ['g', 'G'],
    },
    'KeyH': {
      class: 'button-small',
      inner: true,
      ru: ['р', 'Р'],
      en: ['h', 'H'],
    },
    'KeyJ': {
      class: 'button-small',
      inner: true,
      ru: ['о', 'О'],
      en: ['j', 'J'],
    },
    'KeyK': {
      class: 'button-small',
      inner: true,
      ru: ['л', 'Л'],
      en: ['k', 'K'],
    },
    'KeyL': {
      class: 'button-small',
      inner: true,
      ru: ['д', 'Д'],
      en: ['l', 'L'],
    },
    'Semicolon': {
      class: 'button-small',
      inner: true,
      ru: ['ж', 'Ж'],
      en: [';', ':'],
    },
    'Quote': {
      class: 'button-small',
      inner: true,
      ru: ['э', 'Э'],
      en: ["'", '"'],
    },
    'Enter': {
      class: 'button-small ent',
      inner: false,
      ru: ['Enter', 'Enter'],
      en: ['Enter', 'Enter'],
    },
    'ShiftLeft': {
      class: 'button-small shift-left',
      inner: false,
      ru: ['Shift', 'Shift'],
      en: ['Shift', 'Shift'],
    },
    'KeyZ': {
      class: 'button-small',
      inner: true,
      ru: ['я', 'Я'],
      en: ['z', 'Z'],
    },
    'KeyX': {
      class: 'button-small',
      inner: true,
      ru: ['ч', 'Ч'],
      en: ['x', 'X'],
    },
    'KeyC': {
      class: 'button-small',
      inner: true,
      ru: ['с', 'С'],
      en: ['c', 'C'],
    },
    'KeyV': {
      class: 'button-small',
      inner: true,
      ru: ['м', 'М'],
      en: ['v', 'V'],
    },
    'KeyB': {
      class: 'button-small',
      inner: true,
      ru: ['и', 'И'],
      en: ['b', 'B'],
    },
    'KeyN': {
      class: 'button-small',
      inner: true,
      ru: ['т', 'Т'],
      en: ['n', 'N'],
    },
    'KeyM': {
      class: 'button-small',
      inner: true,
      ru: ['ь', 'Ь'],
      en: ['m', 'M'],
    },
    'Comma': {
      class: 'button-small',
      inner: true,
      ru: ['б', 'Б'],
      en: [',', '<'],
    },
    'Period': {
      class: 'button-small',
      inner: true,
      ru: ['ю', 'Ю'],
      en: ['.', '>'],
    },
    'Slash': {
      class: 'button-small',
      inner: true,
      ru: ['.', ','],
      en: ['/', '?'],
    },
    'ShiftRight': {
      class: 'button-small shift-right',
      inner: false,
      ru: ['Shift', 'Shift'],
      en: ['Shift', 'Shift'],
    },
    'ControlLeft': {
      class: 'button-small ctrl',
      inner: false,
      ru: ['Ctrl', 'Ctrl'],
      en: ['Ctrl', 'Ctrl'],
    },
    'MetaLeft': {
      class: 'button-small win',
      inner: false,
      ru: ['Win', 'Win'],
      en: ['Win', 'Win'],
    },
    'AltLeft': {
      class: 'button-small alt',
      inner: false,
      ru: ['Alt', 'Alt'],
      en: ['Alt', 'Alt'],
    },
    'Space': {
      class: 'button-small space',
      inner: false,
      ru: ['', ''],
      en: ['', ''],
    },
    'AltRight': {
      class: 'button-small alt',
      inner: false,
      ru: ['Alt', 'Alt'],
      en: ['Alt', 'Alt'],
    },
    'ControlRight': {
        class: 'button-small ctrl',
        inner: false,
        ru: ['Ctrl', 'Ctrl'],
        en: ['Ctrl', 'Ctrl'],
      },
    
    'ArrowLeft': {
      class: 'button-small arrow',
      inner: false,
      ru: ['⇐', '⇐'],
      en: ['⇐', '⇐'],
    },
    'ArrowUp': {
        class: 'button-small arrow',
        inner: false,
        ru: ['⇑', '⇑'],
        en: ['⇑', '⇑'],
      },
    'ArrowDown': {
      class: 'button-small arrow',
      inner: false,
      ru: ['⇓', '⇓'],
      en: ['⇓', '⇓'],
    },
    'ArrowRight': {
      class: 'button-small arrow',
      inner: false,
      ru: ['⇒', '⇒'],
      en: ['⇒', '⇒'],
    },
    
  }
